# Function to generate an HTML file with given content
def generate_html_file(filename,content):
    with open(filename, 'w') as file:
        file.write(content)

file_contents = [ 
        ("map-tag.html", ""),
        ("track-tag.html", ""),
        ("video-tag.html", ""),
        ("video-tag.html", ""),
        ("embed-tag.html", ""),
        ("iframe-tag.html", ""),
        ("object-tag.html", ""),
        ("picture-tag.html", ""),
        ("portal-tag.html", ""),
        ("source-tag.html", ""),
        ("source-tag.html", ""),
        ("svg-tag.html", ""),
        ("math-tag.html", ""),
        ("canvas-tag.html", ""),
        ("noscript-tag.html", ""),
        ("script-tag.html", ""),
        ("del-tag.html", ""),
        ("ins-tag.html", ""),
        ("caption-tag.html", ""),
        ("col-tag.html", ""),
        ("colgroup-tag.html", ""),
        ("table-tag.html", ""),
        ("tbody-tag.html", ""),
        ("tfoot-tag.html", ""),
        ("th-tag.html", ""),
        ("thead-tag.html", ""),
        ("tr-tag.html", ""),
        ("button-tag.html", ""),
        ("dialog-tag.html", ""),
        ("fieldset-tag.html", ""),
        ("form-tag.html", ""),
        ("input-tag.html", ""),
        ("label-tag.html", ""),
        ("legend-tag.html", ""),
        ("meter-tag.html", ""),
        ("optgroup-tag.html", ""),
        ("option-tag.html", ""),
        ("output-tag.html", ""),
        ("progress-tag.html", ""),
        ("select-tag.html", ""),
        ("textarea-tag.html", ""),
        ("details-tag.html", ""),
        ("dialog-tag.html", ""),
        ("sammury-tag.html", ""),
        ("form-tag.html", ""),
        ("input-tag.html", ""),
        ("label-tag.html", ""),
        ("legend-tag.html", ""),
        ("meter-tag.html", ""),
        ("optgroup-tag.html", ""),
        ("option-tag.html", ""),
        ("output-tag.html", ""),
        ("progress-tag.html", ""),
        ("select-tag.html", ""),
        ("textarea-tag.html", ""),
        ("slot-tag.html", ""),
        ("template-tag.html", ""),
        ("acronym-tag.html", ""),
        ("applet-tag.html", ""),
        ("bgsound-tag.html", ""),
        ("big-tag.html", ""),
        ("blink-tag.html", ""),
        ("center-tag.html", ""),
        ("dir-tag.html", ""),
        ("font-tag.html", ""),
        ("frame-tag.html", ""),
        ("framset-tag.html", ""),
        ("image-tag.html", ""),
        ("keygen-tag.html", ""),
        ("marquee-tag.html", ""),
        ("menuitem-tag.html", ""),
        ("nobr-tag.html", ""),
        ("noembed-tag.html", ""),
        ("noframes-tag.html", ""),
        ("param-tag.html", ""),
        ("plaintext-tag.html", ""),
        ("rb-tag.html", ""),
        ("rtc-tag.html", ""),
        ("shadow-tag.html", ""),
        ("spacer-tag.html", ""),
        ("strike-tag.html", ""),
        ("tt-tag.html", ""),
        ("xmp-tag.html", "")
        ] 

    # Generate the HTML files
for filename, content in file_contents:
    generate_html_file(filename, content)

print("Five HTML files have been generated successfully!")
